; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Nexa AI Assistant"
#define MyAppVersion "1.0-beta"
#define MyAppPublisher "Ali Adil Waseem"
#define MyAppURL "https://github.com/AliAdilWaseem/Nexa-MyAI"
#define MyAppExeName "Nexa AI.exe"
#define MyAppIcon "assets\icon.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Default installation to D:\Nexa - AI Assistant
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Require admin for install (optional, can change to lowest for per-user)
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog
; Output directory for the compiled setup file
OutputDir=D:\Nexa - AI Assistant
OutputBaseFilename=Nexa_AI_Setup_Beta_v1.0
; Setup wizard icon
SetupIconFile={#MyAppIcon}
; Uninstaller icon (same as app icon)
UninstallDisplayIcon={app}\{#MyAppExeName}
; Compression settings
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
; Enable disk spanning for large installations
DiskSpanning=yes
; Minimum Windows version (Windows 10)
MinVersion=10.0
; Wizard images (optional - comment out if not available)
; WizardImageFile=assets\wizard_image.bmp
; WizardSmallImageFile=assets\wizard_small.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startmenu"; Description: "Create Start Menu shortcut"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; Main executable and all bundled files
Source: "dist\Nexa AI\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\Nexa AI\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Exclude build artifacts
; Source: "dist\Nexa AI\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Start Menu shortcut with icon
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: startmenu
; Desktop shortcut with icon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
; Startup shortcut (minimized on boot)
Name: "{userstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Parameters: "--minimized"; Tasks: startmenu

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean up user data on uninstall (optional)
Type: filesandordirs; Name: "{localappdata}\Nexa AI"
Type: filesandordirs; Name: "{app}\data\logs"
Type: filesandordirs; Name: "{app}\data\weather_cache"

[Code]
// Custom code for installation checks
function InitializeSetup(): Boolean;
begin
  Result := True;
  // Could add checks for .NET, Visual C++ Redistributable, etc.
end;
